### ISSUE TITLE
Add support of img

### ISSUE THREAD

**Issue by vitaly-zdanevich** [grml/grml-rescueboot#20]

**Comment by mika** [comment]
(Continuing from https://github.com/grml/grml/issues/212)

Can you please provide an example of such a `img` file you're talking about?
Does it work for you when renaming such an `.img` file to `.iso`?

**Comment by vitaly-zdanevich** [comment]
https://github.com/debootdevs/deboot/releases/tag/0.2.0

I did not try to rename, it should work?

**Comment by mika** [comment]
See https://github.com/grml/grml-rescueboot/tree/master/debian

**Comment by vitaly-zdanevich** [comment]
> The script looks for ISO images in /boot/grml/ and adds an entry for each image found

> the ISO image needs to support loopback.cfg

No img?

**Comment by zeha** [comment]
I'm sorry, but this is just a waste of everyone's time.
Please find some support forum and ask there.
