### ISSUE TITLE
CUSTOM_BOOTOPTIONS are quoted too much

### ISSUE THREAD

**Issue by gsauthof** [grml/grml-rescueboot#5]
The issue is that `CUSTOM_BOOTOPTIONS` are quoted - `cat /proc/cmdline` of the booted grml system then looks like this:

```
BOOT_IMAGE=/boot/grml64small/... "\x20ssh=secret\x20toram\x20ip=..." nomce
```

And options like `toram` and `ssh=` are not interpreted during startup - seems to be a similar issue to this one: http://ml.grml.org/pipermail/grml/2011-February/011120.html 

The original `/etc/default/grml-rescueboot` contains:

```
CUSTOM_BOOTOPTIONS="ssh=secret nobeep toram ip=... dns=..."
```

I've fetched the 2 grml-rescueboot files via:

```
wget -O /etc/grub.d/42_grml https://raw.github.com/grml/grml-rescueboot/master/42_grml
wget -O /etc/default/grml-rescueboot https://raw.github.com/grml/grml-rescueboot/master/etc/default/grml-rescueboot
```

The regeneration was done like this:

```
# ls /boot/grml
grml64-small_2014.11.iso
# chmod 755 /etc/grub.d/42_grml
# grub2-mkconfig -o /boot/grub2/grub.cfg
```

The host system is CentOS 7

/bin/sh is linked like this:

```
/bin/sh -> bash
```

Version is:

```
GNU bash, version 4.2.45(1)-release (x86_64-redhat-linux-gnu)
```

**Comment by michaellass** [comment]
Because I was also hit by this I sent a pull request to grml-live to fix the grml config. Until that (or some similar change) is merged, the ISOs can be patched relatively easily using bbe:

```
bbe -e "s/\x22\x24\x7B\x6B\x65\x72\x6E\x65\x6C\x6F\x70\x74\x73\x7D\x22/\x20\x24\x7B\x6B\x65\x72\x6E\x65\x6C\x6F\x70\x74\x73\x7D\x20/" -o patched.iso original.iso
```
